name: LagCleaner
version: '1.0.0'
main: com.kim.lagcleaner.LagCleaner
api-version: '1.21'
authors: [ Kim ]
description: A plugin to clean up memory and reduce lag on your Minecraft server
website: https://github.com/yourusername/lagcleaner

commands:
  lag:
    description: Clean server memory
    usage: /<command> [clean]
    permission: lagcleaner.command.lag
    permission-message: You don't have permission to use this command!
  
  rem:
    description: Clean system memory
    usage: /<command> [clean]
    permission: lagcleaner.command.rem
    permission-message: You don't have permission to use this command!
  
  lagcleaner:
    description: LagCleaner main command
    usage: /<command> [reload|info]
    permission: lagcleaner.use
    permission-message: You don't have permission to use this command!

permissions:
  lagcleaner.use:
    description: Allows using all LagCleaner commands
    default: op
    children:
      lagcleaner.command.lag: true
      lagcleaner.command.rem: true
      lagcleaner.reload: true
  
  lagcleaner.command.lag:
    description: Allows using /lag command
    default: op
  
  lagcleaner.command.rem:
    description: Allows using /rem command
    default: op
  
  lagcleaner.reload:
    description: Allows reloading LagCleaner configuration
    default: op
